# 차원 (Dimension)

In [ ]:
# 1번 퀘스트
# 다음 NumPy 배열의 차원 수를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array.ndim)

3


In [ ]:
# 2번 퀘스트
# 1차원 배열 [10, 20, 30, 40, 50, 60]을 2차원 배열로 변환하여 (2, 3) 형태로 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([10,20,30,40,50,60])

print(array.reshape(2,3))

[[10 20 30]
 [40 50 60]]


In [ ]:
# 3번 퀘스트
# 다음 1차원 배열에 새로운 차원을 추가하여 2차원 배열로 변환하고, 최종 배열의 차원 수를 출력하세요.
# `newaxis`를 사용하여 배열의 차원을 추가하고, 새로운 차원에서의 배열 모양을 확인한 후 최종 차원 수를 출력하세요.
import numpy as np
array = np.array([7, 14, 21])

array1 = array[:,np.newaxis]
print("앞에 축을 추가한 array1의 shape:", array1.shape)
print("앞에 축을 추가한 array1의 차원 수:", array1.ndim)

array2 = array[np.newaxis, :]
print("뒤에 축을 추가한 array2의 shape:", array2.shape)
print("뒤에 축을 추가한 array2의 차원 수:", array2.ndim)

앞에 축을 추가한 array1의 shape: (3, 1)
앞에 축을 추가한 array1의 차원 수: 2
뒤에 축을 추가한 array2의 shape: (1, 3)
뒤에 축을 추가한 array2의 차원 수: 2


# Shape

In [ ]:
# 1번 퀘스트
# 주어진 2차원 NumPy 배열의 형태(Shape)를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])

print(array.shape)

(2, 3)


In [ ]:
# 2번 퀘스트
# 1차원 배열 [10, 20, 30, 40, 50, 60]을 (2, 3) 형태로 변경한 후, 새로운 배열의 형태를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([10, 20, 30, 40, 50, 60])

new_array = array.reshape(2,3)
print("new_array shape:",new_array.shape)

new_array shape: (2, 3)


In [ ]:
# 3번 퀘스트
# 다음 3차원 배열의 형태를 변경하여 (3, 2, 2) 형태로 조정하고, 최종 배열의 형태를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])
print(array.shape)
array.resize(3,2,2)
print(array.shape)

(3, 2, 2)
(3, 2, 2)


# 데이터 타입 (Data Type)

In [ ]:
# 1번 퀘스트
# 아래의 NumPy 배열의 데이터 타입을 확인하는 코드를 작성하세요.
import numpy as np
array = np.array([10, 20, 30])
print(array.dtype)

int64


In [ ]:
# 2번 퀘스트
# 정수형 배열 [1, 2, 3]을 부동소수점형 배열로 변환하고, 변환된 배열의 데이터 타입을 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([1,2,3])
print("변환 전 데이터 타입:", array.dtype)

converted_array = array.astype(np.float16)
print("변환 후 데이터 타입:", converted_array.dtype)

변환 전 데이터 타입: int64
변환 후 데이터 타입: float16


In [ ]:
# 3번 퀘스트
# NumPy 배열 [100, 200, 300]을 uint8로 변환한 후, 메모리 사용량(바이트)을 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([100,200,300])
converted_array = array.astype(np.uint8)
print("메모리 사용량(바이트):", converted_array.nbytes)
print(converted_array)

메모리 사용량(바이트): 3
[100 200  44]


# 인덱싱 (Indexing)

In [ ]:
# 1번 퀘스트
# 주어진 1차원 배열에서 첫 번째 요소와 마지막 요소를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([10, 20, 30, 40, 50])
print("첫번째 요소:", array[0]," 마지막 요소:", array[-1])

첫번째 요소: 10  마지막 요소: 50


In [ ]:
# 2번 퀘스트
# 주어진 2차원 배열에서 첫 번째 열과 두 번째 행을 출력하는 코드를 작성하세요.
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("첫 번째 열:", matrix[:,0])
print("두 번째 행:", matrix[1,:])

첫 번째 열: [1 4 7]
두 번째 행: [4 5 6]


In [ ]:
# 3번 퀘스트 **
# 주어진 배열에서 10보다 큰 요소들만 선택하고, 해당 요소들의 인덱스를 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([5, 15, 8, 20, 3, 12])

print(np.where(array>10))

(array([1, 3, 5]),)


# 연산 (Operation)

In [ ]:
# 1번 퀘스트
# 주어진 NumPy 배열에서 요소별(Element-wise) 덧셈을 수행하는 코드를 작성하세요.
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [ ]:
# 2번 퀘스트
# 다음 NumPy 배열에서 브로드캐스팅을 활용하여 각 행에 `[1, 2, 3]`을 더하는 코드를 작성하세요.
import numpy as np
matrix = np.array([[10, 20, 30], [40, 50, 60]])
vector = np.array([1, 2, 3])
print(matrix+vector)

[[11 22 33]
 [41 52 63]]


In [ ]:
# 3번 퀘스트
# 주어진 2차원 NumPy 배열에 대해, 축(axis)을 기준으로 최댓값을 구하고 최종 배열의 차원을 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([[3, 7, 2], [8, 4, 6]])
print("축 0을 기준으로 최대값:",np.max(array, axis=0), " 최종 배열의 차원:", np.max(array, axis=0).ndim)
print("축 1을 기준으로 최대값:",np.max(array, axis=1), " 최종 배열의 차원:", np.max(array, axis=1).ndim)

축 0을 기준으로 최대값: [8 7 6]  최종 배열의 차원: 1
축 1을 기준으로 최대값: [7 8]  최종 배열의 차원: 1


# 유니버셜 함수 (Universal Function)

In [ ]:
# 1번 퀘스트
# 배열 [1, 2, 3, 4]에 대해 NumPy의 유니버설 함수를 사용하여 모든 요소를 제곱한 결과를 출력하는 코드를 작성하세요
import numpy as np
array = np.array([1,2,3,4])

print(np.square(array))

[ 1  4  9 16]


In [4]:
# 2번 퀘스트
# 다음 두 배열의 요소별 합을 계산하고, 결과를 새로운 배열이 아닌 기존 배열에 저장하는 코드를 작성하세요.
import numpy as np
array1 = np.array([10, 20, 30])
array2 = np.array([1, 2, 3])
result = np.empty_like(array1) # 결과를 기록할 기존 배열

np.add(array1, array2, out=result)
print("기준 배열에 저장 :", result)

기준 배열에 저장 : [11 22 33]


In [ ]:
# 3번 퀘스트
# 다음 배열에 대해 NumPy 유니버설 함수를 사용하여 요소별로 자연로그(log)를 계산하고,
# 특정 조건(log 값 > 1)을 만족하는 요소만 출력하는 코드를 작성하세요.
import numpy as np
array = np.array([1, np.e, 10, 100])
print(array[np.log(array) >1])

[ 10. 100.]
